### ISSUE TITLE
Binary to burn

### ISSUE THREAD

**Issue by alexsho** [stefanbode/Sonoff-Tasmota#101]
Hi,
I'd like to test your fork, because the main usage for me is blinds.
The link you provide in the **Readme.md** brings to the regular arendst's Tasmota versions.   
Which binary should i burn to my Sonoff Pro 4ch in order to get your code ?

**Comment by stefanbode** [comment]
Hi Alexo, i do not provide precompiled binaries. Can you compile them on your own? If not I will generate one for the Sonoff Pro4ch.

**Comment by alexsho** [comment]
Yes, please. I will appreciate it very much.
Build for me the binary for the Pro 4ch.

**Comment by stefanbode** [comment]
Uploaded to the /bin directory. Have fun

**Comment by alexsho** [comment]
Thank you very much.

**Comment by alexsho** [comment]
I get error, Upload buffer miscompare.
What does it mean ?
