### ISSUE TITLE
Battery suggestion

### ISSUE THREAD

**Issue by helmar74** [stefanbode/Sonoff-Tasmota#102]
Hi, 

I'm planning to run this Tasmota fork on a Wemos D Mini, connected with a HC-SR04.
The Device should be battery powered.
As a HC-SR04 is connected, I need a 5V battery or battery pack. The battery should have round about 10000mAh
I tried several usb power packs, but unfourtnately all powerpacks I tried had a "auto power down" mode. So it was powering down, when the wemos mini entered deepsleep mode...

Has anyone an suggestion which battery, usb powerpack or battery pack would meet my requirements?

Thanks a lot

Helmar

**Comment by stefanbode** [comment]
Hi Helmar, i have an old one that does not power down. As far as I know, the new ones all have this crazy feature. My battery powered devices are trimmed to 3.3V. Therefore do not work with the distance sensor. Maybe you ask in the main forum. More people there that might have an idea

**Comment by stefanbode** [comment]
Ok, I assume this is my mistake with the last sync to the master. Will be back on Jan 20th and the. Look for the bug. You can also checkout the previous release before the sync. This should work. Sometimes I killed one of my changes after syncing to the master. Should not happen, but does.

**Comment by mbt45** [comment]
Hi Stefan
How long is the duration of the wake time between 2 sleep? Is there a command to extend the time?

**Comment by stefanbode** [comment]
No the idea is to wait for the first successful Teleperiod executed and then goto sleep.

**Comment by mbt45** [comment]
Hi. 

For a probe that works like a charm and I actually  think this should be a included in the official Tasmota. It is a great addition for battery powered sensors. Congratulations
Unfortunately for an Automation here the switch need to do something at a specific regular time it is a little trickier.
I am going to try to write an automation that sends a Deepsleep 0 Mqtt message to try to catch the 10 seconds when the tasmota is on, so the other automations can do their work and then put it back in deepsleep again. I hope it works. 
Actually making a button link on that stop deepsleep mqtt will actually be very useful.

However, thank you so much for that piece of code. My pool temp probe used to have a 3 day battery time before your code, I have put your deepsleep on for every 5 min as tasmota tele does and I am still waiting for the battery to run out. 👍

**Comment by stefanbode** [comment]
Maybe I have an idea that could help. Send a deepsleep 0 to your MQTT Server with the retain flag. Then send a deepsleep 3600 without the retain flag. Now your device go into deepsleep for an hour. After wake up it reads the retained message and stay awake until you send it back to sleep again. This makes it easier to catch the device. Maybe teleperiod 300 also help. The. You have 5 minutes to catch it, but this is not as smart as the first solution. You have to send a deepsleep 3600 again and to bring the device into sleep after operation

**Comment by mbt45** [comment]
Thank you for the response.
You solution looks interesting and probably better, but unfortunately I am
not a real good coder.
So I do not know how to send a MQTT with the retain flag on Hassio.
Do you think making a switch like this would work?

 - id: "Thermo Deepsleep off"
   platform: mqtt
   name: "Deepsleep thermo off"
   command_topic: "cmnd/D1mini/"
   state_topic: "stat/D1mini/"
   payload_on: "deepsleep 0 "
   payload_off: "deepsleep 300 "
   retain: true

By the way a 6700 mAh  battery with normal tasmota worked for 3.5 days.
With you program it worked for 10 day ( x3 time increase).
I am truly grateful for that.

I can now switch to a solar battery an see if it can hold the entire month

**Comment by stefanbode** [comment]
Please download "MQTT SPY". This graphical program let you easily retain (store forever) a message. Regarding your operation time, I still assume you have a big leak of current. On the wemos chips the serial converter is quite energy hungry. even if not needed. My bare ESP8266 with a voltage regulator to 3.3V last for ~9month on an hourly wake-up interval with an NCR18650B 3.7V Li-Ion battery (~3400mAh)

**Comment by mbt45** [comment]
Wow that is a lot of time.  Although I made my wake up every 5 min to
compare with the normal Tasmota Tele.
I am probably going to set it to 10min (should be good enough for a pool)
Unfortunately I intend to use only normal 5v usb batteries so it can be
changed or replaced easily by anyone without electronic knowledge (that
also included myself, just started to learn) so the Wemos module is very
convenient since it can be easily flashed and powered.
It won't be the most energy friendly but for that amount of current it
shouldn't matter much.
I might do one just for the fun of it, if I find the spare time.

My automation of choice now is :
- Wall wiring : Shelly 1 and 2 (shelly UI is great and works MQTT out of
the box without flashing)
- sensors and battery powered stuff: D1mini with YOUR modified TASMOTA  :-)
- Steppers and servos: probably D1 Mini  but I am still searching for the
right easy software for that.

Your software saved my day for sensors. I can probably optimize it but for
now it look very good.

Thanks again

**Comment by mbt45** [comment]
Although  an idea that jumped in my mind.
But have Hassio being able to send an MQTT command to change the deepsleep
would actually be a nice way to automate.
Hassio could change the deepsleep depending on if it is day or night, or
even on specific months or when you are at home and not on vacation.

**Comment by mbt45** [comment]
do you think that would be possible?

**Comment by stefanbode** [comment]
During deepsleep the esp does not get updates. Therefore it is required to retain/save the message in HASSIO. If the ESP wakes up he automatically will update the interval and go to sleep again with the new interval.

**Comment by mbt45** [comment]
Thank you
