### ISSUE TITLE
Sonoff S20 / S26

### ISSUE THREAD

**Issue by goosst** [stefanbode/Sonoff-Tasmota#104]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [ X] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ X] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ X] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ X] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [NA ] Development/Compiler/Upload tools used :
- [ ] Hardware used : 
S20
- [ NA] Provide the output of command ``status 0`` :

Dear,

Thanks a lot for this branch and hard work. 
Is it possible to provide some guidance if it makes sense to implement deepsleep on the S20/S26 sonoff devices?
* Is it useful to implement this on the S20/S26? Or are the remainder of the losses (after using the "light sleep") mainly in the powersupply anyway?
* from the wiki I get: 
> and that for a wakeup as always you have to connect the RST pin with the D0/GPIO16 pin because the wake-up signal is sent through D0/GPIO16 to RST

Is this accessible on the S20/S26 devices? Most of the examples using this branch seem to be using the wemos devices. 

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by stefanbode** [comment]
It should work, because these two pins are available. But maybe hard do wire and solder these together. I have no S20 to my hand to check it, but maybe you have some luck with google. From my point of view this is for sure only a hardware topic. One question: deepsleep only is required and make sense on Batterie powered systems. Therefore I do not see a use-case on the S20.

**Comment by stefanbode** [comment]
hi @goosst , the power consumption is about 0.1A at 5V compared to a phone that uses 1-2A at 5V. Therefore up to 20x more. Therefore the TASMOTA will use a day the same as the smartphone uses for 1h during charge. If you calculate this for a year it is 0.5W * 24h * 365 = 4.2kWh ~ 1.5€ / year.

You can invest time, but this really does not make a big change.
