### ISSUE TITLE
Switchtopic publishes to wrong MQTT prefix

### ISSUE THREAD

**Issue by mrmin24** [stefanbode/Sonoff-Tasmota#106]
I changed the Switchtopic to Sens/Garage when using PIR

But instead of publishing to prefix2/Sens/Garage/Power1 it publishes to prefix1/Sens/Garage/Power1

i.e. it publishes to the topic it is supposed to subscribe to, not the one it publishes to.

Help please.

Thx

**Comment by ascillato** [comment]
It is designed like that. Sorry.

Please, adapt it in your home automation software. Thanks.

If you need further help, please find us in the Tasmota Chat. Thanks

**Comment by mrmin24** [comment]
ok. thx a lot
