### ISSUE TITLE
bin file with pcf8574 support

### ISSUE THREAD

**Issue by Karl-opec** [stefanbode/Sonoff-Tasmota#11]
I commented this already in the closed issue. But perhaps it might be better to open a new issue.

I use your last bin file  with the electrodragon 2 Relay board and a chinese pcf8574 and an 8 relay board.
The relays connected to the pcf8574 are working, the relays onboard don't switch anymore but they show up in the weggui.
Any Idea?

![screenshot_20171117_103837](https://user-images.githubusercontent.com/1394350/32941247-6bb4182e-cb85-11e7-8c29-f04e85c3afd0.png)
![screenshot_20171117_104000](https://user-images.githubusercontent.com/1394350/32941256-74635eda-cb85-11e7-89bd-19dd5845a7d0.png)

**Comment by stefanbode** [comment]
Thanks for informing me. I will check on the weekend. arendst changed a lot during the last weeks on relays. Not very easy to keep the rest working. I had fo change a major portion of the code already. You will get feedback asap

**Comment by stefanbode** [comment]
I found the bug and fixed it. Tested today only with ONE board, but hopefully also working with more than one. BIN files updated

**Comment by Karl-opec** [comment]
Thanks for fixing it. Yes all 10 Relays are switchable now by remote commands.
The two onboard switches of the electrodragon board don't act as in arendst version.

Thanks

**Comment by stefanbode** [comment]
I checked with two relays on the WEMOS and 8 relays on the pcf. For me this worked perfectly though mqtt and webinterface . I have no eletrodragon to verify.

**Comment by Karl-opec** [comment]
Relay switching does also work for me by web and mqtt. 

On the electrodragon board there are two mini switches which can also switch the two relays on the board with the standard arendst software. with yours variant they don't. But it is ok for me. I wanted only mention it. 

Never mind.  Thanks for fixeing the main bug.

**Comment by stefanbode** [comment]
ok, now I understand. I assume 2 GPIO are assigned as SWITCH1 and SWITCH2. They should switch RELAY1 and RELAY2. let me see. should be fixable.

**Comment by Karl-opec** [comment]
[Details of the electrodragon board](http://www.electrodragon.com/w/ESP_Relay_Board_Hardware#Specific_for_Relay_Board) you find here. the switches are on gpio0 and gpio2

**Comment by stefanbode** [comment]
I checked it with GPIO0 on a WEMOS board and everything is running fine. Depending on my switch ON/OFF the relay goes on or off. If you need a toggle mode you need to set SWITCHMODE 3 or 4

![image](https://user-images.githubusercontent.com/16225290/33175762-11ff6f9a-d05d-11e7-8f86-868edd3bf1fd.png)
![image](https://user-images.githubusercontent.com/16225290/33175775-1887ca92-d05d-11e7-8c58-8d4658658b07.png)

**Comment by Karl-opec** [comment]
Could you be so nice and update the bin files to version 5.10.0?

Thanks in advance.

**Comment by stefanbode** [comment]
Yes, done.
