### ISSUE TITLE
Can I install stefanbode fork via OTA?

### ISSUE THREAD

**Issue by micdg96** [stefanbode/Sonoff-Tasmota#114]
Hi, sorry for the stupid question but i'm new in the world of tasmota. In the Wiki I didn't find any instruction on how to install this firmware (I want to install the stefanbode fork in order to controll shutters) on a sonoff dual... Can you give me some explaination on how to do It?

**Comment by jaimemrjm** [comment]
I tried to install this fork by installing Sonota firstly in my Sonoff Touch T1, compiling this fork from Arduino IDE and then WiFi upgrade from Sonota firmware but I had no luck to boot after upgrading. Maybe it works for you.

**Comment by salcabo** [comment]
I'm interested too, can't find the way of uploading into sonoff t1 via ota.

**Comment by jaimemrjm** [comment]
> I'm interested too, can't find the way of uploading into sonoff t1 via ota.

[Sonota allows to install Tasmonta into sonoff T1](https://github.com/mirko/SonOTA/wiki#known-working-configurations)

**Comment by stefanbode** [comment]
OTA is working as in the master branch. Therefore you should not see any differences there

**Comment by bjeram** [comment]
OTA works for me as well. What kind of problem do you have? 
It might e that you want to install Tasmota for the 1st time. 1st time I installed Tasmota using the serial connection because I read that there are problems/is not possible to install Tasmota for the 1st time using OTA (anymore).

**Comment by lsd87** [comment]
I install tasmota  sonoff-mini (Full sonoff is over 500K in size) via serial to overwrite the original then use OTA to load stefans great version

**Comment by micdg96** [comment]
So I have to buy a sonoff dual and then via OTA I can directly install this firmware downloading it from stefanbode GitHub?

**Comment by lsd87** [comment]
If you buy an ITEAD sonoff it will come with EWelink firmware which will not allow OTA of tasmota.
So you have to the serial link upload first (See Tasmota GitHub/youtube for loads of info on uploading)

There is sonOTA which used to work directly with EWelink but last time I look it had been blocked.

BTW. I started off using a dual but I'm going to use the T1's (EU Dual) as it's will be a direct replacement for the current 230V switches in use now (just need to add neutrals to each switch). This gives manual/Auto control and if the home automation crashes (I'm using Hass.io) then the touch buttons can still be used to control the shutter.

**Comment by bjeram** [comment]
I am using Dual R2 with the addition of RF (buttons), so I can also control shutter with RF (up/down).
There is RF support build into tasmota.

**Comment by micdg96** [comment]
Ok i checked on mirko's wiki, for a sonoff dual r2 sonota should work with the firmware 2.0.1. For other firmware I have  to flash by serial. Now I didn't understand if stefanbode fork Is already included in the tasmota firmware that sonota installs via OTA or I have to change to firmware file.

**Comment by jaimemrjm** [comment]
No, it doesn't include in Sonota. You should install stefanbode fork binary *after* sonota installation.

**Comment by bjeram** [comment]
You have Firmware button where you can browse to the binary file

**Comment by micdg96** [comment]
Ok thank you for the help!!

**Comment by micdg96** [comment]
I would like to use a itead sonoff dual (putting only the pcb board into the wall) and connect my phisical switches to the pins button 0 - 1 and ground. Should It work? And also, moving manually the blinds should I see the percentage of opening changing on tasmota page (or on homeassistent if I integrate tasmota on it)?

**Comment by lsd87** [comment]
The binary I got last week from Stefan's zip file does not work, see his wiki shutter section
Go to the bottom of the page to sonoff_template reference. You have to compile the binary yourself.
Both buttons will then work.
HA will see the position if you manually change the shutter using the buttons - use the sketch that Stephan has created

**Comment by lsd87** [comment]
position_topic: stat/sonoff/SHUTTER1 
The is the line that HA uses to keep track of shutter position

**Comment by micdg96** [comment]
Sorry but how to compile by my self the binary file?

**Comment by bjeram** [comment]
Most information can be found on original Tasmota wiki: https://github.com/arendst/Sonoff-Tasmota/wiki
Here is for example how you set up Arduino IDE where you can build binaries yourselF: https://github.com/arendst/Sonoff-Tasmota/wiki/Arduino-IDE

**Comment by micdg96** [comment]
Sorry but i'm finding difficulties... Does the file firmware.sonoff.bin in the bin direcory works for shutters if I upload it through the tasmota user interface? Or do I have to compile following the guide for setting up Arduino IDE downloading the zip file in the code section of stefanbode repo??

**Comment by bjeram** [comment]
In a previous post, you asked about how to compile the binary file, so I've answered this.
But there is precompiled binary:
https://github.com/stefanbode/Sonoff-Tasmota/blob/master/bin/firmware_sonoff.bin
that can be loaded using OTA/ Firmware button in the web interface.

**Comment by lsd87** [comment]
I found that Stefans precompiled one of the external contacts (not sure which one Button 0 or 1) did not work on the DUAL R2 that I had - as per Stefans notes. 
micdg96 If you want the version I did give me an email address and I'll send it to you (347K zipped)

**Comment by micdg96** [comment]
Ok thank you. There is some way to send a private message?

**Comment by lsd87** [comment]
Think I've loaded the binary into GitHub (never used github before !)
[https://github.com/lsd87/Sonoff-DUAL-Binary](url)

**Comment by micdg96** [comment]
Lsd87 thank you really! So with this firmware i Will Be able to use and itead sonoff dual r2 with both phisical switches working (i have to solder the switches on the button pins on the board) if I config like you wrote in the readme?

**Comment by lsd87** [comment]
Its the one I'm using on by dual :-)
