### ISSUE TITLE
MQTT JSON string format issue for .../tele/RESULT

### ISSUE THREAD

**Issue by Markusenz** [stefanbode/Sonoff-Tasmota#115]
Version : 6.3.0.16 stb-1.4(sonoff)

having problems converting the mqtt message from topic  .../tele/RESULT into a JSON object, I suggest to correct the formatting.
currently, the output is
`{"SHUTTER-1":{"POSITION":97, direction:0}}`
but should read
`{"SHUTTER-1":{"POSITION":97, "direction":0}}`

**Comment by bjeram** [comment]
Agree. I introduced this change (for the rules), but I will modify as you suggest and see if the rules are still working.
