### ISSUE TITLE
Versioning & Sync

### ISSUE THREAD

**Issue by electrontube** [stefanbode/Sonoff-Tasmota#118]
It looks like there has been no Sync to TASMOTA for a while, but there were changes to the SB Code that appear not to be reflected in the SB Version Number.

There were erlier Versions that claimed to be up to SB 1.8, the latest three or more Versions report "SB 1.4"

 ???

**Comment by stefanbode** [comment]
Hi, update to current release just uploaded. My versioning always goto 1.0 if there is a new master release. Maybe not the best idea, but this is how it is currently maintained.

**Comment by electrontube** [comment]
Thanks for the update!
