### ISSUE TITLE
MQTT SHUTTER-1

### ISSUE THREAD

**Issue by JagoPir** [stefanbode/Sonoff-Tasmota#122]
Hello,
first of all, congratulations for the job!
I have a problem in bringing the shutter-1 value back to openhab via mqtt (ver 1)
I'm using this code but it does not return any value
```
Number Serranda "apertura  [%.1f W]"
                { mqtt=
                        "
                        <[openhabianpi- mqtt:tasmota/bagno_gianni/serranda/tele/SENSOR:state:JSONPATH(SHUTTER-1)]
                        " 
                }
```
Thank you for your help

**Comment by udo1toni** [comment]
This is because the code is completely wrong :) as this issue tracker is the wrong place to ask openHAB questions either... Please try https://community.openhab.org/ instead.
