### ISSUE TITLE
Additionnal Shutter, commands doesn't works as expected

### ISSUE THREAD

**Issue by calcipher49** [stefanbode/Sonoff-Tasmota#132]
Hi Stefan.
As your fork works perfectly with one shutter, I wanted to configure Sonoff pro to command 2 shutters.
I configured outputs as follows:
Shutter1: Relay 1 to open and Relay2 to close
Shutter2: Relay 3 to open and Relay4 to close
Also I use these parameters:
SetOption14 1
SetOption13 1
BucketSize 2
SetOption80 1
SetOption81 1
ShutterRelay1 1
ShutterRelay2 1

ShutterPosition1 works perfectly to open or close Shutter1 (relays 1 an 2), but ShutterPosition2 fails to activate relays3 and 4 and use (by mistake?) also relays1 and 2.

Log is as follows:
[log.txt](https://github.com/stefanbode/Sonoff-Tasmota/files/2923348/log.txt)

Thanks if you can help if it is a bug or not and correct configuration to use with 2 shutters.

**Comment by stefanbode** [comment]
Easy answer: shutterrelay2 is 3. The. It should work. You define the first relay of the shutter.
