### ISSUE TITLE
Expose as blinds in Google Home

### ISSUE THREAD

**Issue by jokerigno** [stefanbode/Sonoff-Tasmota#136]
Hi,

first of all, again, thank you for your work.

I noticed that since few days google assistant has introduced blinds management

(https://developers.google.com/actions/smarthome/guides/blinds)

Do you think is possible to change exposure from light (actual) to blinds, in order to use better voice commands?

Thank you in advance

**Comment by stefanbode** [comment]
Hi, yes for sure this is a great idea. I'm already a bit behind the actual version. Too much preparation for next week HMI fare trade in Hannover.

**Comment by jokerigno** [comment]
I saw you updated the release. Any news on this?

**Comment by stefanbode** [comment]
Not yet. I got the info that the new template page on the webinterface does not work currently. I have to check this. Currently we are now in sync again with the master branch. This also means that the interlock mechanism now works as defined in the master branch. I removed my implementation.

**Comment by stefanbode** [comment]
I try to get an idea on how to implement this and gave up. If you have some hints on how to do it please be welcome and help me.

**Comment by jokerigno** [comment]
Don't ask how or why. But since last google assistant sync cover are exposed as cover also in google home app!

**Comment by titomontes** [comment]
> Don't ask how or why. But since last google assistant sync cover are exposed as cover also in google home app!

So how would one go about and set this for google home??

**Comment by stefanbode** [comment]
@jokerigno : It would be great if you can enhance the wiki for the shutter and explain how you get it working with google home. This will help all the others too

**Comment by jokerigno** [comment]
well: I don't know. I simply exposed shutters in google home and they were exposed as lights (so I was saying "turn on - off" .

Then they simply became covers. And I didn't change anything in my config, only sync my devices.

I'm still with version 6.1.3 and didn't update because I'm scared to loose it !
