### ISSUE TITLE
Warning in MQTT after update to version 6.5.0.3

### ISSUE THREAD

**Issue by ihavenonick** [stefanbode/Sonoff-Tasmota#141]
I have this warning in IOBroker Log from sonoff adapter (MQTT):
 
`warn: sonoff.0 Cannot parse data "STATE": _{"Time":"2019-04-17T19:38:20","Uptime":"0T00:00:17","Vcc":3.187,"SleepMode":"Dynamic","Sleep":100,"LoadAvg":9,"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":2,"SSId":"FRITZ!","BSSId":"44:4E:6D:58:11:01","Channel":13,"RSSI":92,"LinkCount":1,"Downtime":"0T00:00:07","DeepSleep":0,"Heap":20600"}}_ - SyntaxError: Unexpected string in JSON at position 286`

otherwise everything is normal

**Comment by stefanbode** [comment]
Thanks for bringing this up. it is fixed with the current change

**Comment by ihavenonick** [comment]
it works
