### ISSUE TITLE
no more support for 2MB flash device with Core 2.3.0 

### ISSUE THREAD

**Issue by ihavenonick** [stefanbode/Sonoff-Tasmota#145]
Servus Stefan,

Tasmota  lässt keine Modifikation der Flashgröße mehr zu, zumindest beim 2.3.0er Core. Mit dem neuen 2.5.1er Core läuft es wie gehabt. 
Das ist auch das Problem an Deiner aktuellen Version, da gibts kein Core 2.5.1.
Könntest Du bitte Deine Fork an die aktuelle Tasmota Version anpassen, damit ich wieder den vollen Flash bei meinen Geräten nutzen kann?

Mehr dazu kannst du [hier](https://github.com/arendst/Sonoff-Tasmota/issues/5825) nachlesen.

Ich habe die platformio.ini durch die der aktuelen Tasmota ersetzt und den Core 2.5.1 verwendet, so läuft auch Deine Fork wieder bei mir mit 2MB Flash.
![grafik](https://user-images.githubusercontent.com/36501310/57984957-433d0680-7a61-11e9-9b83-bdb2ae9073d3.png)

**Comment by stefanbode** [comment]
Just uploaded the new synced version. 2.5.1 core now available

**Comment by ihavenonick** [comment]
perfekt und danke
