### ISSUE TITLE
Wait for Motorstop 500

### ISSUE THREAD

**Issue by maxgiordan** [stefanbode/Sonoff-Tasmota#155]
<<<<<<< HEAD
=======
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

>>>>>>> 8f585b7f5354b19aff4bc6d1f238df4588d5693f
Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x] Hardware used : sonoff 4chpro r2
- [x] If a pre-compiled release or development binary was used, which one? : Sonoff-Tasmota 6.5.0.11 stb-1.5 by Theo Arends
- [x] You have tried latest release or development binaries? : yes
- [x] Provide the output of command ``status 0`` :
```
14:59:51 CMD: status 0
14:59:51 SRC: WebConsole from 192.XXX.XXX.XXX
14:59:51 RSL: Received Topic /status, Data Size 1, Data 0
14:59:51 RSL: Group 0, Index 1, Command STATUS, Data 0
14:59:51 MQT: stat/king_room_shutter/STATUS = {"Status":{"Module":0,"FriendlyName":["Sonoff","Sonoff2","Sonoff3","Sonoff4"],"Topic":"king_room_shutter","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":1}}
14:59:51 MQT: stat/king_room_shutter/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:15:24","StartupUTC":"2019-06-18T12:44:27","Sleep":50,"CfgHolder":4617,"BootCount":26,"SaveCount":2137,"SaveAddress":"F8000"}}
14:59:51 MQT: stat/king_room_shutter/STATUS2 = {"StatusFWR":{"Version":"6.5.0.11 stb-1.5(sonoff)","BuildDateTime":"2019-05-21T19:05:05","Boot":7,"Core":"STAGE","SDK":"2.2.2-dev(c0eb301)"}}
14:59:51 MQT: stat/king_room_shutter/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":4,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["ZWifi",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["0002C029","280500000100000000000000000000000000","C0000200"]}}
14:59:51 MQT: stat/king_room_shutter/STATUS4 = {"StatusMEM":{"ProgramSize":573,"Free":428,"Heap":22000,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000809","0FDAE394","040783A0","23B617CC","01003BC0"]}}
14:59:51 MQT: stat/king_room_shutter/STATUS5 = {"StatusNET":{"Hostname":"king_room_shutter-1804","IPAddress":"192.XXX.XXX.XXX","Gateway":"192.XXX.XXX.XXX","Subnetmask":"255.255.255.0","DNSServer":"192.XXX.XXX.XXX","Mac":"XX:XX:XX:XX:XX:XX","Webserver":2,"WifiConfig":4}}
14:59:51 MQT: stat/king_room_shutter/STATUS6 = {"StatusMQT":{"MqttHost":"192.XXX.XXX.XXX","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_DBC70C","MqttUser":"XXXXXXX","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
14:59:51 MQT: stat/king_room_shutter/STATUS7 = {"StatusTIM":{"UTC":"Tue Jun 18 12:59:51 2019","Local":"Tue Jun 18 14:59:51 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+02:00","Sunrise":"05:46","Sunset":"21:56"}}
14:59:51 MQT: stat/king_room_shutter/STATUS10 = {"StatusSNS":{"Time":"2019-06-18T14:59:51","SHUTTER-1":{"position":100, "direction":0}}}
14:59:51 MQT: stat/king_room_shutter/STATUS11 = {"StatusSTS":{"Time":"2019-06-18T14:59:51","Uptime":"0T00:15:24","SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","Wifi":{"AP":1,"SSId":"XXXXXXX","BSSId":"XX:XX:XX:XX:XX:XX","Channel":11,"RSSI":84,"LinkCount":1,"Downtime":"0T00:00:04","DeepSleep":0,"Heap":23560}}}
14:59:54 WIF: Checking connection...
14:59:54 WIF: Connected
```

**(Please, remember to close the issue when the problem has been addressed)**

Hi, my big problem: I use a sonoff 4chpro r2 with tasmota forked by stefan bode (thank you very much, a fantastic job!) and I have shutter that, randomly, rise and fall by themselves. I immediately thought of mqtt retain problems but, after excluding the mqtt communication, problem didn't disappear.
In the weblog, just before the ghost switching, it appears to me:

> 09:24:18 Wait for Motorstop 500
09:24:18 MQT: tele/king_room_shutter/STATE = {“Time”:“2019-06-17T09:24:18”,“Uptime”:“0T21:29:47”,“SleepMode”:“Dynamic”,“Sleep”:0,“LoadAvg”:999,“POWER1”:“ON”,“POWER2”:“OFF”,“POWER3”:“OFF”,“POWER4”:“OFF”,“Wifi”:{“AP”:1,“SSId”:“Wifi”,“BSSId”:“XX:XX:XX:XX:XX:XX”,“Channel”:11,“RSSI”:46,“LinkCount”:1,“Downtime”:“0T00:00:06”,“DeepSleep”:0,“Heap”:26048}}
09:24:18 MQT: stat/king_room_shutter/RESULT = {“POWER1”:“ON”}
09:24:18 MQT: stat/king_room_shutter/POWER1 = ON (retained)
09:24:18 MQT: stat/king_room_shutter/SHUTTER1 = 100 (retained)
09:24:18 MQT: tele/king_room_shutter/STATE = {“Time”:“2019-06-17T09:24:18”,“Uptime”:“0T21:29:47”,“SleepMode”:“Dynamic”,“Sleep”:0,“LoadAvg”:999,“POWER1”:“OFF”,“POWER2”:“OFF”,“POWER3”:“OFF”,“POWER4”:“OFF”,“Wifi”:{“AP”:1,“SSId”:“Wifi”,“BSSId”:“XX:XX:XX:XX:XX:XX”,“Channel”:11,“RSSI”:46,“LinkCount”:1,“Downtime”:“0T00:00:06”,“DeepSleep”:0,“Heap”:22848}}
09:24:18 MQT: stat/king_room_shutter/RESULT = {“POWER1”:“OFF”}
09:24:18 MQT: stat/king_room_shutter/POWER1 = OFF (retained)
09:24:18 MQT: tele/king_room_shutter/RESULT = {“SHUTTER-1”:{“position”:100, “direction”:0}}
09:25:11 Wait for Motorstop 500
09:25:11 MQT: tele/king_room_shutter/STATE = {“Time”:“2019-06-17T09:25:11”,“Uptime”:“0T21:30:40”,“SleepMode”:“Dynamic”,“Sleep”:0,“LoadAvg”:999,“POWER1”:“ON”,“POWER2”:“OFF”,“POWER3”:“OFF”,“POWER4”:“OFF”,“Wifi”:{“AP”:1,“SSId”:“Wifi”,“BSSId”:“XX:XX:XX:XX:XX:XX”,“Channel”:11,“RSSI”:44,“LinkCount”:1,“Downtime”:“0T00:00:06”,“DeepSleep”:0,“Heap”:26048}}
09:25:11 MQT: stat/king_room_shutter/RESULT = {“POWER1”:“ON”}
09:25:11 MQT: stat/king_room_shutter/POWER1 = ON (retained)
09:25:11 MQT: stat/king_room_shutter/SHUTTER1 = 100 (retained)
09:25:11 MQT: tele/king_room_shutter/STATE = {“Time”:“2019-06-17T09:25:11”,“Uptime”:“0T21:30:40”,“SleepMode”:“Dynamic”,“Sleep”:0,“LoadAvg”:999,“POWER1”:“OFF”,“POWER2”:“OFF”,“POWER3”:“OFF”,“POWER4”:“OFF”,“Wifi”:{“AP”:1,“SSId”:“Wifi”,“BSSId”:“XX:XX:XX:XX:XX:XX”,“Channel”:11,“RSSI”:44,“LinkCount”:1,“Downtime”:“0T00:00:06”,“DeepSleep”:0,“Heap”:22848}}
09:25:11 MQT: stat/king_room_shutter/RESULT = {“POWER1”:“OFF”}
09:25:11 MQT: stat/king_room_shutter/POWER1 = OFF (retained)
09:25:11 MQT: tele/king_room_shutter/RESULT = {“SHUTTER-1”:{“position”:100, “direction”:0}}
09:25:11 Wait for Motorstop 500
09:25:12 MQT: tele/king_room_shutter/STATE = {“Time”:“2019-06-17T09:25:12”,“Uptime”:“0T21:30:41”,“SleepMode”:“Dynamic”,“Sleep”:0,“LoadAvg”:999,“POWER1”:“ON”,“POWER2”:“OFF”,“POWER3”:“OFF”,“POWER4”:“OFF”,“Wifi”:{“AP”:1,“SSId”:“Wifi”,“BSSId”:“XX:XX:XX:XX:XX:XX”,“Channel”:11,“RSSI”:48,“LinkCount”:1,“Downtime”:“0T00:00:06”,“DeepSleep”:0,“Heap”:26048}}
09:25:12 MQT: stat/king_room_shutter/RESULT = {“POWER1”:“ON”}
09:25:12 MQT: stat/king_room_shutter/POWER1 = ON (retained)
09:25:12 MQT: stat/king_room_shutter/SHUTTER1 = 100 (retained)
09:25:12 MQT: tele/king_room_shutter/STATE = {“Time”:“2019-06-17T09:25:12”,“Uptime”:“0T21:30:41”,“SleepMode”:“Dynamic”,“Sleep”:0,“LoadAvg”:999,“POWER1”:“OFF”,“POWER2”:“OFF”,“POWER3”:“OFF”,“POWER4”:“OFF”,“Wifi”:{“AP”:1,“SSId”:“Wifi”,“BSSId”:“XX:XX:XX:XX:XX:XX”,“Channel”:11,“RSSI”:46,“LinkCount”:1,“Downtime”:“0T00:00:06”,“DeepSleep”:0,“Heap”:22848}}
09:25:12 MQT: stat/king_room_shutter/RESULT = {“POWER1”:“OFF”}
09:25:12 MQT: stat/king_room_shutter/POWER1 = OFF (retained)
09:25:12 MQT: tele/king_room_shutter/RESULT = {“SHUTTER-1”:{“position”:100, “direction”:0}}

Seems to wait for the engine to stop ... but I don't understand.
I have enabled weblog 4 and the next ghost I publish the results.
Help me, I'm going crazy ...

**Comment by stefanbode** [comment]
The motorstop is just a delay after switching one relay off on switch on the other one. It is a delay do let the motor physical stop before it gets power in the other direction. This explanation for the motor stop.  

And i do not understand the log. Looks crazy. Maybe weblog 5 can help, because then we should see which function switches the relay. I assume you do nothing. Question is why this thing operates automatically.

**Comment by maxgiordan** [comment]
Thanks Stefan, for me it is a real honor to receive your help: your work is truly exceptional ... and I tell you with sincerity, believe me.
I have been waiting for hours for ghost switching but, as always happens (at 6 am this morning for example shutter up and down like crazy), when you need ... nothing.
Instead on the second sonoff, identical configuration, here it is:
Shutter all open, suddenly

> 18:15:43 APP: Button2 level 1-0
18:15:43 SRC: Button
18:15:43 Switched relay: 2 by Button
18:15:43 Wait for Motorstop 500
18:15:44 Shutter 0: Target: 0, powerstatelocal 2
18:15:44 MQT: stat/bed_room_shutter/RESULT = {"POWER2":"ON"}
18:15:44 MQT: stat/bed_room_shutter/POWER2 = ON (retained)
18:15:44 Shutter 0: Real Pos: 55888, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 0.1  [s]
18:15:44 APP: Button2 level 0-1
18:15:44 CFG: Saved to flash at F9, Count 235, Bytes 3824
18:15:45 Shutter 0: Real Pos: 53648, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 1.1  [s]
18:15:46 Shutter 0: Real Pos: 51408, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 2.0  [s]
18:15:47 Shutter 0: Real Pos: 49168, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 3.0  [s]
18:15:48 Shutter 0: Real Pos: 46928, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 4.0  [s]
18:15:49 Shutter 0: Real Pos: 44688, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 5.0  [s]
18:15:50 Shutter 0: Real Pos: 42448, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 6.0  [s]
18:15:51 Shutter 0: Real Pos: 40208, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 7.0  [s]
18:15:52 Shutter 0: Real Pos: 37968, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 8.1  [s]
18:15:53 Shutter 0: Real Pos: 35728, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 9.1  [s]
18:15:54 Shutter 0: Real Pos: 33488, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 10.1  [s]
18:15:55 Shutter 0: Real Pos: 31248, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 11.1  [s]
18:15:55 WIF: Checking connection...
18:15:55 WIF: Connected
18:15:56 Shutter 0: Real Pos: 29008, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 12.1  [s]
18:15:57 Shutter 0: Real Pos: 26768, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 13.1  [s]
18:15:58 Shutter 0: Real Pos: 24528, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 14.1  [s]
18:15:59 Shutter 0: Real Pos: 22288, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 15.1  [s]
18:16:00 Shutter 0: Real Pos: 20048, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 16.1  [s]
18:16:01 Shutter 0: Real Pos: 17808, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 17.1  [s]
18:16:02 Shutter 0: Real Pos: 15568, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 18.1  [s]
18:16:03 Shutter 0: Real Pos: 13328, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 19.1  [s]
18:16:04 Shutter 0: Real Pos: 11088, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 20.1  [s]
18:16:05 Shutter 0: Real Pos: 8848, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 21.1  [s]
18:16:06 Shutter 0: Real Pos: 6608, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 22.0  [s]
18:16:07 Shutter 0: Real Pos: 4368, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 23.1  [s]
18:16:08 Shutter 0: Real Pos: 2128, Target 0, source: , start-pos: 100 %, direction: -1, rtcshutter: 24.1  [s]
18:16:09 Shutter 0: Real Pos. 0, Stoppos: 0, relay: 1, direction -1, pulsetimer: 0, rtcshutter: 25.0 [s], operationtime 0
18:16:09 MQT: stat/bed_room_shutter/SHUTTER1 = 0 (retained)
18:16:09 SRC: 
18:16:09 Switched relay: 2 by 
18:16:09 MQT: stat/bed_room_shutter/RESULT = {"POWER2":"OFF"}
18:16:09 MQT: stat/bed_room_shutter/POWER2 = OFF (retained)
18:16:09 MQT: tele/bed_room_shutter/RESULT = {"SHUTTER-1":{"position":0, "direction":0}}
18:16:09 CFG: Saved to flash at F8, Count 236, Bytes 3824
18:16:15 WIF: Checking connection...
18:16:15 WIF: Connected

After a few minutes, suddenly

> 18:29:41 APP: Button1 level 1-0
18:29:41 SRC: Button
18:29:41 Switched relay: 1 by Button
18:29:41 Wait for Motorstop 500
18:29:41 Shutter 0: Target: 56000, powerstatelocal 1
18:29:41 MQT: stat/bed_room_shutter/RESULT = {"POWER1":"ON"}
18:29:41 MQT: stat/bed_room_shutter/POWER1 = ON (retained)
18:29:41 Shutter 0: Real Pos: 100, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 0.1  [s]
18:29:41 APP: Button1 level 0-1
18:29:41 APP: Button1 level 1-0
18:29:41 SRC: Button
18:29:41 Switched relay: 1 by Button
18:29:41 Shutter 0: Switch OFF motor. Target: 100, source: Button, powerstate_local 0, switchedRelay 1, manual change 1
18:29:41 Shutter 0: Target: 100, powerstatelocal 0
18:29:41 MQT: stat/bed_room_shutter/RESULT = {"POWER1":"OFF"}
18:29:41 MQT: stat/bed_room_shutter/POWER1 = OFF (retained)
18:29:41 Shutter 0: Real Pos. 200, Stoppos: 0, relay: 0, direction 1, pulsetimer: 0, rtcshutter: 0.1 [s], operationtime 0
18:29:41 MQT: stat/bed_room_shutter/SHUTTER1 = 0 (retained)
18:29:41 MQT: tele/bed_room_shutter/RESULT = {"SHUTTER-1":{"position":0, "direction":0}}
18:29:42 APP: Button1 level 0-1
18:29:42 APP: Button1 level 1-0
18:29:42 SRC: Button
18:29:42 Switched relay: 1 by Button
18:29:42 Wait for Motorstop 500
18:29:42 Shutter 0: Target: 56000, powerstatelocal 1
18:29:42 MQT: stat/bed_room_shutter/RESULT = {"POWER1":"ON"}
18:29:42 MQT: stat/bed_room_shutter/POWER1 = ON (retained)
18:29:42 CFG: Saved to flash at F7, Count 237, Bytes 3824
18:29:42 APP: Button1 level 0-1
18:29:43 Shutter 0: Real Pos: 1300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 0.6  [s]
18:29:44 Shutter 0: Real Pos: 3300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 1.6  [s]
18:29:45 Shutter 0: Real Pos: 5300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 2.5  [s]
18:29:46 Shutter 0: Real Pos: 7300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 3.5  [s]
18:29:47 Shutter 0: Real Pos: 9300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 4.5  [s]
18:29:48 Shutter 0: Real Pos: 11300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 5.5  [s]
18:29:49 Shutter 0: Real Pos: 13300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 6.5  [s]
18:29:50 Shutter 0: Real Pos: 15300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 7.5  [s]
18:29:51 Shutter 0: Real Pos: 17300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 8.6  [s]
18:29:52 Shutter 0: Real Pos: 19300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 9.6  [s]
18:29:53 Shutter 0: Real Pos: 21300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 10.6  [s]
18:29:54 Shutter 0: Real Pos: 23300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 11.6  [s]
18:29:55 Shutter 0: Real Pos: 25300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 12.6  [s]
18:29:56 Shutter 0: Real Pos: 27300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 13.6  [s]
18:29:56 WIF: Checking connection...
18:29:56 WIF: Connected
18:29:57 Shutter 0: Real Pos: 29300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 14.6  [s]
18:29:58 Shutter 0: Real Pos: 31300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 15.6  [s]
18:29:59 Shutter 0: Real Pos: 33300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 16.6  [s]
18:30:00 Shutter 0: Real Pos: 35300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 17.6  [s]
18:30:01 Shutter 0: Real Pos: 37300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 18.6  [s]
18:30:02 Shutter 0: Real Pos: 39300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 19.6  [s]
18:30:03 Shutter 0: Real Pos: 41300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 20.6  [s]
18:30:04 Shutter 0: Real Pos: 43300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 21.6  [s]
18:30:05 Shutter 0: Real Pos: 45300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 22.6  [s]
18:30:06 Shutter 0: Real Pos: 47300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 23.6  [s]
18:30:07 Shutter 0: Real Pos: 49300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 24.5  [s]
18:30:08 Shutter 0: Real Pos: 51300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 25.6  [s]
18:30:09 Shutter 0: Real Pos: 53300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 26.6  [s]
18:30:10 Shutter 0: Real Pos: 55300, Target 56000, source: , start-pos: 0 %, direction: 1, rtcshutter: 27.6  [s]
18:30:10 Shutter 0: Real Pos. 56000, Stoppos: 100, relay: 0, direction 1, pulsetimer: 0, rtcshutter: 27.9 [s], operationtime 0
18:30:10 MQT: stat/bed_room_shutter/SHUTTER1 = 100 (retained)
18:30:10 SRC: 
18:30:10 Switched relay: 1 by 
18:30:10 MQT: stat/bed_room_shutter/RESULT = {"POWER1":"OFF"}
18:30:10 MQT: stat/bed_room_shutter/POWER1 = OFF (retained)
18:30:10 MQT: tele/bed_room_shutter/RESULT = {"SHUTTER-1":{"position":100, "direction":0}}
18:30:11 CFG: Saved to flash at F6, Count 238, Bytes 3824
18:30:16 WIF: Checking connection...
18:30:16 WIF: Connected

So I understand that the buttons are the problem. I thought about the 433 mhz and then I did a reset of the frequencies: I thought that maybe inadvertently pressing the wall button twice I could activate the pairing function and the sonoff got some kind of frequency ... well ... it seems to me absurd...

**Comment by maxgiordan** [comment]
and a little while ago:

> 21:42:42 APP: Button1 level 1-0
21:42:42 SRC: Button
21:42:42 Switched relay: 1 by Button
21:42:42 Wait for Motorstop 500
21:42:42 Shutter 0: Target: 56000, powerstatelocal 1
21:42:42 MQT: stat/bed_room_shutter/RESULT = {"POWER1":"ON"}
21:42:42 MQT: stat/bed_room_shutter/POWER1 = ON (retained)
21:42:42 Shutter 0: Real Pos. 56000, Stoppos: 100, relay: 0, direction 1, pulsetimer: 0, rtcshutter: 0.0 [s], operationtime 0
21:42:42 MQT: stat/bed_room_shutter/SHUTTER1 = 100 (retained)
21:42:42 SRC: 
21:42:42 Switched relay: 1 by 
21:42:42 MQT: stat/bed_room_shutter/RESULT = {"POWER1":"OFF"}
21:42:42 MQT: stat/bed_room_shutter/POWER1 = OFF (retained)
21:42:42 MQT: tele/bed_room_shutter/RESULT = {"SHUTTER-1":{"position":100, "direction":0}}
21:42:42 APP: Button1 level 0-1
21:42:42 APP: Button1 level 1-0
21:42:42 SRC: Button
21:42:42 Switched relay: 1 by Button
21:42:42 Wait for Motorstop 500
21:42:43 Shutter 0: Target: 56000, powerstatelocal 1
21:42:43 MQT: stat/bed_room_shutter/RESULT = {"POWER1":"ON"}
21:42:43 MQT: stat/bed_room_shutter/POWER1 = ON (retained)
21:42:43 Shutter 0: Real Pos. 56000, Stoppos: 100, relay: 0, direction 1, pulsetimer: 0, rtcshutter: 0.1 [s], operationtime 0
21:42:43 MQT: stat/bed_room_shutter/SHUTTER1 = 100 (retained)
21:42:43 SRC: 
21:42:43 Switched relay: 1 by 
21:42:43 MQT: stat/bed_room_shutter/RESULT = {"POWER1":"OFF"}
21:42:43 MQT: stat/bed_room_shutter/POWER1 = OFF (retained)
21:42:43 MQT: tele/bed_room_shutter/RESULT = {"SHUTTER-1":{"position":100, "direction":0}}
21:42:43 APP: Button1 level 0-1
21:42:43 APP: Button1 level 1-0
21:42:43 SRC: Button
21:42:43 Switched relay: 1 by Button
21:42:43 Wait for Motorstop 500
21:42:43 Shutter 0: Target: 56000, powerstatelocal 1
21:42:43 MQT: stat/bed_room_shutter/RESULT = {"POWER1":"ON"}
21:42:43 MQT: stat/bed_room_shutter/POWER1 = ON (retained)
21:42:43 Shutter 0: Real Pos. 56000, Stoppos: 100, relay: 0, direction 1, pulsetimer: 0, rtcshutter: 0.0 [s], operationtime 0
21:42:43 MQT: stat/bed_room_shutter/SHUTTER1 = 100 (retained)
21:42:43 SRC: 
21:42:43 Switched relay: 1 by 
21:42:43 MQT: stat/bed_room_shutter/RESULT = {"POWER1":"OFF"}
21:42:43 MQT: stat/bed_room_shutter/POWER1 = OFF (retained)
21:42:43 MQT: tele/bed_room_shutter/RESULT = {"SHUTTER-1":{"position":100, "direction":0}}
21:42:43 APP: Button1 level 0-1
21:42:51 WIF: Checking connection...
21:42:51 WIF: Connected

**Comment by stefanbode** [comment]
Ok very is interesting. I agree that this looks like a hardware issue. Please remove the cable from the switch button and check again. As mentioned it does not look like a software issue at the current point.

**Comment by maxgiordan** [comment]
So, I decided to reset everything, both sonoff, erase memory and sent directly 
> Sonoff-Tasmota 6.5.0.11 stb-1.5. 

I made configuration via serial and then I reassembled everything to the wall without screwing anything. I also did a 433 frequency reset.
Since problem seems to come from buttons, I thought of some of my imperfect welding (actually like a pig!) for cables that lead to the wall buttons and I also thought of possible contacts on the sonoff as there are 3 cables passing on the back and so I just put the lid down.
For the moment both sonoffs work well, except that once the down button (from the wall) didn't work for about 15 minutes (o weblog of this problem, as if I hadn't pressed the button.....terror!) and then started working again.
Stefan, I apologize to you and everyone because it really is a problem that has nothing to do with your beautiful fork and therefore, if you feel it's correct to close this issue, I agree otherwise I'll update you soon about situation.
Thank you for your help and for your work!

**Comment by maxgiordan** [comment]
Hi everyone, today the problems listed above seem to have disappeared. A total reset and further distancing the buttons from the sonoff cover seems to have solved all the problems.
Thanks for your help.

**Comment by maxgiordan** [comment]
Hi everyone, I have to reopen for an update: I think it's helpful for those who have the same problem as me.
For about an hour the sonoff is like crazy without me touching anything::

> 09:59:57 APP: Button1 level 1-0
09:59:57 SRC: Button
09:59:57 Switched relay: 1 by Button
09:59:57 Wait for Motorstop 500
09:59:58 Shutter 0: Target: 56000, powerstatelocal 1
09:59:58 MQT: stat/king_room_shutter/RESULT = {"POWER1":"ON"}
09:59:58 MQT: stat/king_room_shutter/POWER1 = ON (retained)
09:59:58 Shutter 0: Real Pos. 56000, Stoppos: 100, relay: 0, direction 1, pulsetimer: 0, rtcshutter: 0.1 [s], operationtime 0
09:59:58 MQT: stat/king_room_shutter/SHUTTER1 = 100 (retained)
09:59:58 SRC: 
09:59:58 Switched relay: 1 by 
09:59:58 MQT: stat/king_room_shutter/RESULT = {"POWER1":"OFF"}
09:59:58 MQT: stat/king_room_shutter/POWER1 = OFF (retained)
09:59:58 MQT: tele/king_room_shutter/RESULT = {"SHUTTER-1":{"position":100, "direction":0}}
09:59:58 APP: Button1 level 0-1
09:59:58 APP: Button1 level 1-0
09:59:58 SRC: Button
09:59:58 Switched relay: 1 by Button
09:59:58 Wait for Motorstop 500
09:59:59 Shutter 0: Target: 56000, powerstatelocal 1
09:59:59 MQT: stat/king_room_shutter/RESULT = {"POWER1":"ON"}
09:59:59 MQT: stat/king_room_shutter/POWER1 = ON (retained)
09:59:59 Shutter 0: Real Pos. 56000, Stoppos: 100, relay: 0, direction 1, pulsetimer: 0, rtcshutter: 0.1 [s], operationtime 0
09:59:59 MQT: stat/king_room_shutter/SHUTTER1 = 100 (retained)
09:59:59 SRC: 
09:59:59 Switched relay: 1 by 
09:59:59 MQT: stat/king_room_shutter/RESULT = {"POWER1":"OFF"}
09:59:59 MQT: stat/king_room_shutter/POWER1 = OFF (retained)
09:59:59 MQT: tele/king_room_shutter/RESULT = {"SHUTTER-1":{"position":100, "direction":0}}
09:59:59 APP: Button1 level 0-1


In practice I had the shutter at 50% and suddenly it got up to 100% and continued like this for about 40 minutes until I opened the sonoff and reset the 433 frequencies. The sonoff started to work properly again.
So I think I've isolated the problem and done full justice to tasmota and Stefan's fork.
Now, I ask you, how can I exclude the IR function?
I've read several posts but they don't talk about ch4 pro, who can help me?

**Comment by stefanbode** [comment]
Maybe you copy the definition of the ch4pro to chr4pro-ir and then remove the GPIO definition for the IR sensor. If you need more help let me know.

**Comment by maxgiordan** [comment]
> Maybe you copy the definition of the ch4pro to chr4pro-ir and then remove the GPIO definition for the IR sensor. If you need more help let me know.

Oh yes yes, I need more help, thanks. 
What exactly you mean, I'm sorry, I'm at a very low level!

**Comment by stefanbode** [comment]
WifiConfig = 4, Please learn from the wiki: https://github.com/arendst/Sonoff-Tasmota/wiki/Commands

**Comment by tonyado** [comment]
Hi to everyone, I have the same problem, I have two Sonoff 4CH pro R2 and after a while if I closed rollershutters, randomly it open again. I have installed other Sonoff dual R2 without any problems. In the log I found wait for motorstop 500. I'll try to post complete log. Thanks for your hard works

**Comment by stefanbode** [comment]
the motorstop 500 is only to ensure that the motor does not change direction without stopping 0.5sek inbetween. nothing else. For sure this has nothing to do with a sudden movement
