### ISSUE TITLE
Flashing stefanbode fails

### ISSUE THREAD

**Issue by adizag** [stefanbode/Sonoff-Tasmota#156]
Trying to flash stefanbode firmware. I understand i must flash the sonoff_minimal.bin before.

If I'm flashing  the sonoff_minimal.bin from stefanbode bin folder - the switch will not recover from restart. Stuck...
If I'm flashing the original sonoff_minimal.bin, the flashing succeeded but trying to then flash stefabode firmware I'm  getting: 
"sonoff firmware upgrade:
Upload Failed

Magic byte is not 0xE9"

The switch is generic tuya curtain switch.

Thanks in advance!!!

**Comment by adizag** [comment]
Is there a reason why not flashing firmware directly by ftdi?

**Comment by udo1toni** [comment]
You will only need to flash minimal.bin if flashing via OTA.

**Comment by adizag** [comment]
The downloaded file was damaged....
Downloaded again - working!

Thanks!!!!

**Comment by adizag** [comment]
The downloaded file was damaged....
Downloaded again - working!

Thanks!!!!
