### ISSUE TITLE
Adax Wifi heater with ESP8266 and NXP 8574TS I2C 

### ISSUE THREAD

**Issue by DenielTorres** [stefanbode/Sonoff-Tasmota#157]
**Have you look for this feature in other issues and in the wiki?**
Yes
**Is your feature request related to a problem? Please describe.**
I was looking for information on flashing my board for Adax branded wifi electric heaters with ESP8266 chips, and it turns out it has these kinds of chips as well. 

**Describe the solution you'd like**
I saw that your fork basically supports this but only for relay functioning if I'm not mistaken. Was wondering if it could be repurposed/added as a more generic function. 

**Additional context**
Thanks very much in advance for taking the time and reading this through!!!

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by DenielTorres** [comment]
Here is an image of the board if that helps: 
![IMG_20190711_195110](https://user-images.githubusercontent.com/19772214/61085232-04f41000-a430-11e9-8d76-533cc99d5fba.jpg)

**Comment by stefanbode** [comment]
sorry never seen before. Maybe you ask in the main forum of TASMOTA.

**Comment by trommegutten** [comment]
> Here is an image of the board if that helps:
> ![IMG_20190711_195110](https://user-images.githubusercontent.com/19772214/61085232-04f41000-a430-11e9-8d76-533cc99d5fba.jpg)
@DenielTorres Did you try flashing this with Tasmota?

**Comment by costinchirita** [comment]
Did you managed to flash it with Tasmota?

**Comment by trommegutten** [comment]
No, Sorry. I’ve sold The heaters.

**Comment by costinchirita** [comment]
Ok, thanks!
