### ISSUE TITLE
PlatformIO v4.0: Problem compiling with 2.3.0 core

### ISSUE THREAD

**Issue by snakuzzo** [stefanbode/Sonoff-Tasmota#158]
Hi Stefan,
there was a problem compiling using core 2.3.0 + platformio 4.0.
Related issue on tasmota project: [#6073](https://github.com/arendst/Sonoff-Tasmota/issues/6073)

This problem was solved few minutes ago with this merge on tasmota project: [#6087](https://github.com/arendst/Sonoff-Tasmota/commit/583e10f1e1482b5604cf0f29946413c89dd6fc86)

Please...can you merge the code?

Thank you

**Comment by titomontes** [comment]
The problem has been solved from Platformio´s side. You can close this, and use Platformio 4.0.

Cheers
