### ISSUE TITLE
COMMAND: webPassword

### ISSUE THREAD

**Issue by matteo2019** [stefanbode/Sonoff-Tasmota#160]
using this guide I can't access the sonoff. Why?

WebPassword

Show current web server password
0 = disable use of password for WebUI
1 = reset password to firmware default (WEB_PASSWORD)
<value> = set WebUI password for user WEB_USERNAME (32 char limit)
Default WEB_USERNAME is admin.

**Comment by stefanbode** [comment]
No idea.

**Comment by matteo2019** [comment]
Dando il comando "webpassword on" dal sonoff non c'è alcun modo di accedervi.
Ho risolto inserendo anticipatamente dall'ide di arduino la password e dopo flash il fork sul sonoff.

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________
