### ISSUE TITLE
open and close roller shutters with percentage timers.

### ISSUE THREAD

**Issue by matteo2019** [stefanbode/Sonoff-Tasmota#161]
I use the fork stefanbode on dual sonoff.  I have to open / close the shutters with the timers.  Up to this point everything works.  The problem is to have the timers open at a certain percentage.  For example: at 6.00 o'clock the timer and must close 10% of the shutter.  At 7 o'clock the timer must increase the closure by 10% more.  and at 8 o'clock I want a timer that opens the whole shutter.  (these are just examples, my schedules are different)

**Comment by stefanbode** [comment]
Shutterposition is not supported in rules.

**Comment by matteo2019** [comment]
can't you associate a position with a timer?
________________________________

**Comment by stefanbode** [comment]
As mentioned before all shuttercomands are not available in automation. The idea is fine but I never reviewed what is required to be part of the rules framework. Without: no chance.

**Comment by matteo2019** [comment]
I'll explain better to avoid misunderstandings, unfortunately I'm not English.  I have 2 timers now.  A lift lowers the shutter completely at 13, When the sun comes.  The second timer lowers the shutter at 7pm when the sun has completely gone.  If I want to raise the blind at 50% at 18.00, can't I?

**Comment by matteo2019** [comment]
I'll explain better to avoid misunderstandings, unfortunately I'm not English.  I have 2 timers now.  One lowers the shutter completely at 13, When the sun comes.  The second timer raises the shutter at 7 pm when the sun has completely gone.  If I want to raise the blind at 50% at 18.00, can't I?

**Comment by snakuzzo** [comment]
Now you can't. As explained before, at this time, shuttercommands arn't available in automations.
You can just open or close

**Comment by matteo2019** [comment]
ok clear.  If the article is updated in the future.
________________________________
