### ISSUE TITLE
Only with one button the timer is triggered, the other is just on/off

### ISSUE THREAD

**Issue by markus-fehling** [stefanbode/Sonoff-Tasmota#166]
Hi Team, I flashed the latest(?) version 6.6.0.1 stb-1.5(sonoff) on sonoff T1, 2channel
Set SETOPTION80 1, SETOPTION81 1, INTERLOCK 1,2
Only with one button the timer is triggered, and interlock does not work with my setup
18:12:53 MQT: stat/sonoff/RESULT = {"POWER2":"ON"}
18:12:53 MQT: stat/sonoff/POWER2 = ON
18:12:57 MQT: stat/sonoff/RESULT = {"POWER2":"OFF"}
18:12:57 MQT: stat/sonoff/POWER2 = OFF
18:12:58 Wait for Motorstop 500
18:12:58 MQT: stat/sonoff/RESULT = {"POWER1":"ON"}
18:12:58 MQT: stat/sonoff/POWER1 = ON
18:12:58 Shutter 0: Real Pos: 9500, Target 20000, source: WebGui, start-pos: 47 %, direction: 1, rtcshutter: 0.1  [s]
18:12:59 Shutter 0: Real Pos: 11600, Target 20000, source: WebGui, start-pos: 47 %, direction: 1, rtcshutter: 1.1  [s]
18:13:00 Shutter 0: Real Pos: 13700, Target 20000, source: WebGui, start-pos: 47 %, direction: 1, rtcshutter: 2.1  [s]
18:13:01 Shutter 0: Real Pos: 15600, Target 20000, source: WebGui, start-pos: 47 %, direction: 1, rtcshutter: 3.1  [s]
18:13:02 MQT: stat/sonoff/RESULT = {"POWER1":"OFF"}
18:13:02 MQT: stat/sonoff/POWER1 = OFF

thanks for help, Markus

**Comment by stefanbode** [comment]
interlock is a standard TASMOTA feature. I do not understand your problem. as far as I know setoption80 is not required anymore. only setoption81 to enable the shutter.

**Comment by stefanbode** [comment]
regarding to your log above: this is correct fom the point of view, that POWER2 is on. Now you Switch POWER1 on. This causes FIRST POWER2=off, wait 0,5sec and then POWER1 on to move in the opposite direction. with a higher loglevel you can also see WHO is triggering the relay.

**Comment by stefanbode** [comment]
With the new TASMOTA firmware the interlock has changed. Please sut in the following two commands to get it workin
```
INTERLOCK 1
INTERLOCK 1,2
```
The first one will ENABLE, the second one will et the group.
