### ISSUE TITLE
Shutterproblem with switching from 100%

### ISSUE THREAD

**Issue by AlexanderSch90** [stefanbode/Sonoff-Tasmota#171]
Deutsch; Hallo zusammen,
ich nutze einen Sonoff T1 mit Sonoff-Tasmota 6.6.0.1 stb-1.5 zur Rolladensteuerung.
Folgendes Problem habe ich mit bislang allen getesteten Versionen:
Ich nutze die Rollade zur Verdunkelung bei Sonneneinstrahlung. Dabei fährt die Rollade tagsüber auf 40% und abends wieder auf 100%. Jedesmal, wenn die Rollade auf 100% fährt, öffnet sich die Rollade ein Stückchen weniger. Nach einer Woche ist die Rollade halb unten, obwohl mir Tasmota 100% anzeigt. Wenn ich die Rollade jedoch einmal auf 0% fahre und dann wieder auf 100% geht sie wieder ganz auf.  Würde ich die Rolladen jeden Tag einmal ganz runter und hochfahren, wäre das Problem nicht vorhanden. Diese Lösung möchte ich jedoch nicht nutzen. Wie kann ich das Problem lösen? Oder kannst du das Problem mit einem Softwareupdate lösen? 

Englisch: Hello everybody,
I use a Sonoff T1 with Sonoff-Tasmota 6.6.0.1 stb-1.5 for shutter control.
I have the following problem with all tested versions so far:
I use the shutter for darkening in sunlight. The roller shutter moves during the day to 40% and in the evening back to 100%. Every time the roller shutter moves to 100%, the roller shutter opens a little less. After a week, the shutter is halfway down, although Tasmota shows me 100%. However, once I get the roller shutter to 0% and then back to 100%, it goes up completely again. If I were to shut down the shutters every day, the problem would not exist. However, I do not want to use this solution. How can I solve the problem? Or can you solve the problem with a software update?

**Comment by stefanbode** [comment]
Will answer in English, so others can benefit. This happens typically because the motor operates slower if it pulls the shutter up. Therefore you can define openduration and closeduration. By changing one of them you can fix your problem. You can put in values with an accuracy of 1/10 of a second. Just move up and down between 25% and 50% and fix one value until you reach the same position. Should take less than 5 minutes.
