### ISSUE TITLE
Abbruch bei Verwendung von de-DE

### ISSUE THREAD

**Issue by roesl** [stefanbode/Sonoff-Tasmota#18]
Leider bricht die Kompilierung ab, wenn ich als Sprachauswahl DE angebe.
Woran liegt das ?

Viele Grüße
Georg

**Comment by stefanbode** [comment]
Ich habe das gerade noch mal getestet und es funktioniert mit dem aktuellen Release bei mir. bitte mal eine Fehlermeldung dabei legen.
