### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by ihategitasdfasdf** [stefanbode/Sonoff-Tasmota#190]
I am unable to find a bin file modified by stefanbode to support Shutters to upload to Sonoff T1 EU 2gang.

After looking and reading for over a hour, I did not find absollutely any text on how to install this firmware. Nor where to find it. Then again, it took me 5 minutes just to register to post this question.

If I take a file from stefanbode/Sonoff-Tasmota Bin - it is a standard one. I looked around, found sonoff_Dual_R2_6.6.0.3_stb-1.6.bin - nope, this is standard but in German. Whatever I did, no Shutters mentioned, no slider, commands are unknown, no changed signiture... I flashed them with cable erasing flash.

So I am either downloading wrong files or do not undestand how to activate hidden Shutters feature. Apprantly I have few qeustions.

1. where from can I download a stefanbode Shutters version of soniff.bin? I prefer core 2_3_0 since later are annoying to make initial WLAN connection. But, not a problem, I will take anything. If it matters, I need it for Sonoff T1 Eu 2 Gang and Sonoff Dual R2.

2. Should I see a slider on its own or I must do something mystically?

2. Can fw be uploaded OTA over the standard sonoff.bin or must I take it from the wall again?

3. Am I right to expect signiture on the main Web page (when I connect to the Sonoff device) will differ from a standard one (Sonoff-Tasmota 6.6.0 by Theo Arends).

4. Am I wrong, or there really is no text available explaining where to get this file nor how to install it?

**Comment by stefanbode** [comment]
Hi, welcome to the maker world. This is a special branch of the TASMOTA firmware. All general information you will find there: https://github.com/arendst/Sonoff-Tasmota
Take a look in the wiki pages. Same procedure here. If you want to know how to configure the shutter take a look on the right side when clicking the wiki. Or follow the wiki link on the readme.
No there is no windows installer or anything similar convenient. This is tough maker stuff and you handle with high voltage. Maybe you should buy something ready to use from HOMEMATIC for example. The bin files are.....tataaaa in the /bin directory. Please use the sonoff.bin. No right click. Just left click. otherwhise you get an HTML page
