### ISSUE TITLE
Can´t connect to WIFI after upload your Firmware

### ISSUE THREAD

**Issue by MMeinhardt1** [stefanbode/Sonoff-Tasmota#199]
Hi Stefan,

i have uploaded your sonoff-basic.bin firmware file to my Teepao Curtainswitch. After the successfully upload the switch starts with an own WiFi Hotspot.
I entered my WiFi data, saved it and my data did not seem to be saved after the reboot because the teepao still starts with its own WiFi hotspot.
Do you have any idea how I can solve my problem.

many thanks

**Comment by stefanbode** [comment]
Yes my bin files are broken. Please compile at you own or wait until Monday..

**Comment by stefanbode** [comment]
There is a DIV0 error. Will fix it in a minute with a new upload
