### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by mrmin24** [stefanbode/Sonoff-Tasmota#2]
Hi,

Ok, I missed the //#define USE_PCF8574  previously but now I get a compile error like I am missing some files. 

![image](https://cloud.githubusercontent.com/assets/5115612/25295574/5e77d812-26e4-11e7-817a-36f248af3d59.png)

**Comment by mrmin24** [comment]
Thanks it is working now

Great job

**Comment by bnharvey** [comment]
@mrmin24 
Hi mrmin24,
                   I'm having the same compile issues. What did you do to resolve them?
Thanks

**Comment by mrmin24** [comment]
I think the release was updated to include the missing files at one stage, so I did not do anything. The last release compiled fine. @bnharvey
