### ISSUE TITLE
Add multi-PZEM support - 3-phase support

### ISSUE THREAD

**Issue by stefanbode** [stefanbode/Sonoff-Tasmota#20]
In Germany all houses are connected through a three phase power connection. To measure the complete energy usage it is required to measure all three phases. Instead of using 3 ESP8266 and PZEM-004T there is some convenience to connect all 3 PZEM to one ESP.

The trick is to use 3 TX lines communicating all over ONE RX line, because the ESP does not support more.

On Hardware wire you have to remove resistor R15 at TWO of the three devices. Please see: https://github.com/apreb/eNode/issues/1#issuecomment-354369777

**Comment by roblad** [comment]
Hi,

Do you plan to came back with that ?

**Comment by stefanbode** [comment]
Yes,  I have the devices already on my table and made some initial changes to support multiple devices already. My plan is to finalize and test at the weekend. I will use them productive also personally.

**Comment by roblad** [comment]
Hi,
I am still waiting from China

**Comment by stefanbode** [comment]
Really nasty. I got one working smoothly but still not successful getting values from the second one. As soon as there are TWO devices connected no more responses on the RX. Still debugging.

**Comment by roblad** [comment]
Hi,

Probably you need to plug 3 of them

**Comment by stefanbode** [comment]
Hi rob, due to toooooo many problems I will not include this into my branch. To many side effects I do not understand.

**Comment by roblad** [comment]
Hi,


Any progress ?

**Comment by stefanbode** [comment]
No, currently I would classify it with too complex for me. I will cancel this and measure the e phases with three wemos minis.

**Comment by roblad** [comment]
Hi,

Then me to :-)

**Comment by roblad** [comment]
Hi,

Have seen that ?

https://github.com/arendst/Sonoff-Tasmota/issues/2315#issuecomment-384643624

May be there is an solution n ?

**Comment by roblad** [comment]
Work is going :-)

https://github.com/arendst/Sonoff-Tasmota/issues/2315#issuecomment-385266151

**Comment by stefanbode** [comment]
Fully included in master firmware
