### ISSUE TITLE
SHUTTER50PERCENT not work

### ISSUE THREAD

**Issue by carlosribeiro** [stefanbode/Sonoff-Tasmota#201]
in version 6.6.0.10 the SHUTTER50PERCENT command does not work. gives the result of the console "unknown"

**Comment by stefanbode** [comment]
yes, Theo has renamed in TASMOTA Master the command to shuttersethalfway. I will update the wiki. Please take a look at the new calibration option, if intrested. Also documented in the wiki

**Comment by snakuzzo** [comment]
Hi @stefanbode....rollershutter configuration wiki was deleted ? I can't find the guide...the old page was removed ?

**Comment by stefanbode** [comment]
Yes this is now part of Tasmota. The wiki is here https://github.com/arendst/Sonoff-Tasmota/wiki/Blinds-and-Roller-Shades

**Comment by snakuzzo** [comment]
Great!!! :)
Thank you

**Comment by snakuzzo** [comment]
@stefanbode I missed this update...when this function was included in Tasmota?

**Comment by jokerigno** [comment]
Hi stefanbode, what it the best way to move from your fork to official tasmota? 
I mean I think that If I reflash my sonoffr2 I will loose al my config, including shutter time and percentage for 50% so I will have to restart from scratch for every blind. Am I right?

Or maybe there's some tip that you can share with use helping migrating? 

Thank you in advance

**Comment by stefanbode** [comment]
Depend on. If you use one of the later releases you will not loose anything. Just give it a try. If you loose I am very sorry. You have to go through this one time
