### ISSUE TITLE
Vcc in state

### ISSUE THREAD

**Issue by Gisbert1** [stefanbode/Sonoff-Tasmota#205]
Dear Stefan,

in arendst Tasmota branch, there is in State the Vcc of the device:
`12:43:51 MQT: tele/Lux.Ostseite/STATE = {"Time":"1970-01-11T12:43:51","Uptime":"10T12:07:33","Vcc":3.169,"SleepMode":"Dynamic","Sleep":250,"LoadAvg":16,"Wifi":{"AP":1,"SSId":"IoTXXXXXX","BSSId":"XX:EC:DA:3E:A8:YY","Channel":3,"RSSI":36,"LinkCount":1,"Downtime":"0T00:03:23"}}`

How can I get the Vcc reading in your branch?
I like to see when the voltage of the battery powered device drops down; at least it's try to get an early warning.

Best Regards
Gisbert

**Comment by meingraham** [comment]
#define USE_ADC_VCC                              // Display Vcc in Power status.

This is disabled by default so that ADC0 can be used as a user input. If you enable internal Vcc, the ADC0 input cannot be used.

**Comment by Gisbert1** [comment]
Found it here: [https://github.com/stefanbode/Sonoff-Tasmota/blob/master/sonoff/my_user_config.h](url)
I need to compile the firmware, but I do not know how to do this. I'm using Arduino.
Can you guide me?

Best Regards
Gisbert

**Comment by meingraham** [comment]
Oh, yikes. You haven't looked at any of the Tasmota documentation?

Start here - https://github.com/arendst/Tasmota/wiki/Prerequisites

Use Gitpod to compile.
