### ISSUE TITLE
MQTT Report during movement

### ISSUE THREAD

**Issue by kabongsteve** [stefanbode/Sonoff-Tasmota#209]
I use MQTT to connect to HASS and there is no MQTT reporting of position changes while its moving.

I added the following code to the ShutterReportPosition() method and this resolved the above.

This means I can see the movement in HASS while its moving

~Line 349 (after AddLog_P2()

      uint8_t position =  ShutterRealToPercentPosition(Shutter.real_position[i], i);
      Response_P(PSTR("{"));
      ResponseAppend_P(JSON_SHUTTER_POS, i+1, position, Shutter.direction[i]);
      ResponseJsonEnd();
      MqttPublishPrefixTopic_P(RESULT_OR_TELE, mqtt_data);

**Comment by stefanbode** [comment]
Yes makes sense. Will be merged in the next commit
