### ISSUE TITLE
DeepSleep consumption

### ISSUE THREAD

**Issue by Bojkas1985** [stefanbode/Sonoff-Tasmota#210]
Hello,

I have made a meter reading according to Gemu2015, but deep sleep is not solved much. I need the reading to work on the battery.
After setting deepsleep wemos falls asleep, but after measurement I found that while sleeping, it consumes 20mA. I don't use or know how to use RTC. Can RTC consumption below 1mA be achieved without RTC? Power LED consumes 0.3mA. The load is 65mA. I need it to work on the battery for months.

Thank you
Ivica

**Comment by stefanbode** [comment]
The problem of the Wemos is the usb interface and a bit the voltage regulator. You cannot really avoid this. Therefore for battery powered devices I use bare esp8266 without any blabla. Then the consumption is on micro amp.
