### ISSUE TITLE
Calibration 2nd shutter

### ISSUE THREAD

**Issue by Fabio7586** [stefanbode/Sonoff-Tasmota#212]
Hello,
thank you for your great work!
I have a question: how start to calibrate 2 shutter (3 and 4 relays) on a sonoff 4ch pro r2?
I already have activated second slider and it works with 3 and 4 relays so i don't know how set duration, position and etc.., Can you help me making a little example of what i have to put in console?

**Comment by stefanbode** [comment]
All commands suport the index. therefore `shutteropenduration2 25.4` will set for shutter 2 the duration to 25.4 seconds. Works on all commands
