### ISSUE TITLE
WS2812 - Add MQTT command to bulk load of patterns

### ISSUE THREAD

**Issue by Boby-b** [stefanbode/Sonoff-Tasmota#29]
Would it be possible to add a way of loading 'pattern' for all pixcells in the LED string as:
RRGGBB1,RRGGBB2...RRGGBBN --> px1,px2...pxN

Arendst declines as it is 'too much hassle' in his issue [#1790](https://github.com/arendst/Sonoff-Tasmota/issues/1790).
The idea is to use that feature for making 'big 7-segment digits display'.

I guess there will be a lack or RAM for that and the my proposal for solutions is:
 - combining a number of physical pixcells as 'virt.pixcell'  - (ex.each 5 px --> 1 vpix)
 - Then load pattern to vpix-es:
RRGGBB1,RRGGBB2...RRGGBBN --> vpx1,vpx2...vpxN

Example for one 7-segment big digit (5 pixcells for each segment):
 - define new param: vpixcel-llenght=5
 - physical pixcells - 35 (px0-px34)
 - resulting virtual pixcells - 7 (vpx0-vpx6)

Then loading a desired 7-segment pattern (and desired color as well) with:
RRGGBB0,RRGGBB0...RRGGBB6 --> vpx0,vpx1...vpx6

Thanks.
Borislav Bangov.

**Comment by stefanbode** [comment]
For sure you need to store the information somewhere in the flash and not in the bin file itself. Totally agree to arendst. Your guess regarding lack of RAM is definitely valid. Actual re remaining RAM is something between 21k - 5k depending on the compiler options. You guess that the room for fancy transformations is limited. I don't think it could be managed on the ESP8266. The ESP32 should be able to handle this. Much more features and space.
