### ISSUE TITLE
Pulsetimers

### ISSUE THREAD

**Issue by mrmin24** [stefanbode/Sonoff-Tasmota#3]
Hi,

There are still only 4 pulsetimers available for PCF8574 setup. This is not ideal especially for irrigation.

Thanks

**Comment by stefanbode** [comment]
Hi, this can be changed easily in the standard already in sonoff.ino. OK?

#define MAX_PULSETIMERS        4            // Max number of supported pulse timers

**Comment by mrmin24** [comment]
Yes, I will test this too. I suppose it is worth having a" IFDEF USE_PCF8574" to adjust these to 8 or more.

**Comment by stefanbode** [comment]
There is an additional hardcoded line in sonoff.ino: line 1373 somewhere here:

This is hardcoded &3 (Binary 11) and needs to be flexible. 

`    pulse_timer[(device -1)&(1<<(MAX_PULSETIMERS-1)-1)] = (power & mask) ? sysCfg.pulsetime[(device -1)&(1<<(MAX_PULSETIMERS-1)-1)] : 0;`

**Comment by mrmin24** [comment]
I tested your latest baseline and the timers are working, but it seems that if you activate the nth timer and the n + 4th time (e.g.1 and 5 or 2 and 6) at the same time, the nth relay never switches off. If you activate any other timer with nth timer, it works fine

**Comment by stefanbode** [comment]
Fixed with 5.1.4 update
