### ISSUE TITLE
No distance in the sonoff-adapter witch HC-SR04

### ISSUE THREAD

**Issue by RamsesIoBroker** [stefanbode/Sonoff-Tasmota#31]
Hi and thank you for this project.

I use your software on a nodeMCU with ESP8266. On the web page I see the correct value and the ioBroker also get the distance. But I have the problem that there is no line with a distance value under the object sonoff.0

I use iobroker.admin 3.3.5 and sonoff-adapter 2.0.2

![01](https://user-images.githubusercontent.com/37696863/38206768-eb916f60-36ab-11e8-8c67-fb499a89c8f4.png)

![02](https://user-images.githubusercontent.com/37696863/38207492-56a1edd2-36ae-11e8-85a7-6951bb134be6.png)

![03](https://user-images.githubusercontent.com/37696863/38206781-f99f0054-36ab-11e8-9ef1-f7211a7c2a51.png)

**Comment by stefanbode** [comment]
Is this democitz? As you can see, I report the value inside the teleperiod as json value distance. If you give me an idea where you need it, i can make a change

**Comment by RamsesIoBroker** [comment]
No domoticz. 
I thought that the value will be shown like temperature, humidity or the vcc and RSSI in our case. Like the normal behaviour of the sonoffs. 
If I look in the log I see that every report of a value will be followed by a stateChange command but there is nothing behind the distance message. Is this normal?

**Comment by stefanbode** [comment]
SR04 is now replaced by the official version form main branch.
