### ISSUE TITLE
Will the fork be merged back to the original Sonoff-Tasmota including the PCF8574

### ISSUE THREAD

**Issue by knopserl** [stefanbode/Sonoff-Tasmota#32]
Hi Stefan, I like your fork, because I use it with a ESP01, a PCF8574 module and a 8 port relay-bank - see the attached picture. It works fine.
My question is, if your enhancements mainly the PCF8574 will be merged back to the original Sonoff-Tasmota project from arendst? I have seen, that you are in tight contact with him.

![8-port-relay](https://user-images.githubusercontent.com/36055354/38211195-f9bdd1a6-36b9-11e8-9996-6bd6cead35c2.jpg)

**Comment by stefanbode** [comment]
Great to see. Maybe arendst will add the fork if fix also the input functionality and the trigger. Both are currently not working. Ok the input might work but the trigger for sure not

**Comment by knopserl** [comment]
Is there a PR at the original project open to merge it? I have not seen it.

**Comment by stefanbode** [comment]
No, in this case I had to separate this change from all the others. Too much work.

**Comment by stefanbode** [comment]
The SR04 support is now in the main project. From time to time changes will get it to the main.
