### ISSUE TITLE
HS-SR04 Wires are twisted change ECHO <-> TRIG

### ISSUE THREAD

**Issue by jenluvsem** [stefanbode/Sonoff-Tasmota#35]
Hey, 
I've uploaded your firmware to Wemos D1 mini and no matter how I define pins I'm getting message "HS-SR04 Wires are twisted change ECHO <-> TRIG" on console output. 
Any idea?

Thanks and regards,
Przemek.

**Comment by stefanbode** [comment]
The model requires 5V on VCC. Please double check you have the voltage at the sensor

**Comment by jenluvsem** [comment]
I know the reason for this info but not sure if it should work that way. This message appears also when sensor is not perpendicular to surface..

**Comment by stefanbode** [comment]
SR04 is now part of the official Tasmota project. Changed all sources to the main branch. Any issues must now we fixed there.
