### ISSUE TITLE
deepsleep command not exists

### ISSUE THREAD

**Issue by roblad** [stefanbode/Sonoff-Tasmota#39]
Hi,

After upgrade deepsleep is lost

22:26:29 MQT: stat/zewnetrzne/RESULT = {"Command":"Unknown"}
22:26:40 CMD: deepsleep 1200
22:26:40 MQT: stat/zewnetrzne/RESULT = {"Command":"Unknown"}

I think that should be like this in sonoff.ino line 872

    else if (CMND_DEEPSLEEP == command_code ) {

      if ((data_len > 0) && (payload32 >= 0) ) {

        Settings.deepsleep = (uint32_t)payload32;

instead 

    else if (!strcmp_P(type,PSTR("DEEPSLEEP"))) {
      if ((data_len > 0) && (payload32 >= 0) ) {
        Settings.deepsleep = payload32;

and added in i18n.h

#define D_CMND_DEEPSLEEP "DeepSleep"

and in sonoff.ino line 82

//STB mod
  CMND_GPIO, CMND_GPIOS, CMND_PWM, CMND_PWMFREQUENCY, CMND_PWMRANGE, CMND_COUNTER, CMND_COUNTERTYPE, CMND_COUNTERDEVIDER, CMND_MQTTENABLE,
//end
  CMND_COUNTERDEBOUNCE, CMND_SLEEP, CMND_DEEPSLEEP, CMND_UPGRADE, CMND_UPLOAD, CMND_OTAURL, CMND_SERIALLOG, CMND_SYSLOG,

result is:

23:18:15 CMD: deepsleep
23:18:15 MQT: stat/podlewaczka/RESULT = {"DeepSleep":"-1 (-1)"}

23:18:53 CMD: deepsleep 0
23:18:53 MQT: stat/podlewaczka/RESULT = {"DeepSleep":"0 (0)"}

23:26:52 CMD: deepsleep
23:26:52 MQT: stat/zewnetrzne/RESULT = {"DeepSleep":"1200 (1200)"}

**Comment by stefanbode** [comment]
oh yes, found already yesterday too. I have no idea why, but now fixed it in the way it should be with all the other commands. See my latest checkin from this morning. Also take your chirp code. Like!!

**Comment by roblad** [comment]
Hi, is it possible to add config parameter to set deepsleep on or off for i.e. switching it off permamently?

**Comment by stefanbode** [comment]
Hi Rob, one way is to use one of the GPIO ports for this. I copied the behavior of EPSEASY here. On the other side, you can set it to 0 which is equal to set it off.
