### ISSUE TITLE
PCF8574 with Sonoff SV relay switching

### ISSUE THREAD

**Issue by mrmin24** [stefanbode/Sonoff-Tasmota#5]
When running the PCF8574 on the SV, the relay 1 is obviously the onboard relay. 

The 8 other relays work just fine as well. 

The problem is that when the relay one is switched off, the relay 5 and sometimes 9 is switched on by itself. relay 9 (relay 8 on PCF8574) is not configured at this stage. It is set as input 

Then also if relay 5 is switched off in turn, relay 9 also switches off. Again there is a dependancy between the nth and n + 4th relay just as on pulsetimers

The behaviour changes when relay 9 is defined as output and then does not switch on and off. 

The relay 5 behaviour seems to alternate. So switches on and then off again on each Relay 1 off sequence.

**Comment by mrmin24** [comment]
Hi,

Any chance you could look at this?

thanks

**Comment by stefanbode** [comment]
Hmm, quite strange. You use the pulsetimers? I do the same on wemos with all 8 relays. I already found a bug that interfere with GPIO0. Please can you send me your complete setup to reproduce. I assume you use the latest version

**Comment by mrmin24** [comment]
This is on the Sonoff SV. Yes using pulsetimers. There seems to be some sort of bitmask or shifting problem. This seems to be related to #3

![capture2](https://cloud.githubusercontent.com/assets/5115612/26028315/34b41b44-381e-11e7-993c-2970f7605046.PNG)
![capture1](https://cloud.githubusercontent.com/assets/5115612/26028314/33f17a44-381e-11e7-9d53-6c00aa05bd9c.PNG)


![capture3](https://cloud.githubusercontent.com/assets/5115612/26028320/67fa6738-381e-11e7-93ce-3418b65a3912.PNG)

**Comment by mrmin24** [comment]
any chance you could look at this?

thanks

**Comment by stefanbode** [comment]
I'm currently on holiday. Be back next week.

Von meinem iPad gesendet

Am 25.05.2017 um 21:59 schrieb mrmin24 <notifications@github.com<mailto:notifications@github.com>>:


any chance you could look at this?

thanks

**Comment by stefanbode** [comment]
I changed some behavior that may cause the interference with the I2C relays and the GPIO relays. Additional upgrade to the latest arendst branch. Can you check, if this now works for you?

**Comment by mrmin24** [comment]
Update to version 5.1.5. Still same behaviour when switching relay1, relay 5 switches everytime relay1 switches off.

**Comment by stefanbode** [comment]
@mrmin24 : To enable the usage of the onboard relays 1-4 there where major code adjustments required to get rid of several side effects. I did test it with 2 PCF8574 and up to 4 relays and I was able to reproduce your error before. Now all 20 relays behave as they should. Also, the bouncing is away and I have removed the library to save code.

**Comment by mrmin24** [comment]
@stefanbode Hi, nice work thanks. I am busy testing. So var so good. I have 9 relays including the on-board relay on the SV.
