### ISSUE TITLE
PCF8574 = MCP23S08

### ISSUE THREAD

**Issue by jsponz** [stefanbode/Sonoff-Tasmota#54]
Hi,

Could I use the same code for MCP23S08?

The functionality of the chip is the same.

Thanks!

**Comment by MadDoct** [comment]
And, if possible, and probably easier (i2c), mcp23008 and mcp23017? Thanx

**Comment by stefanbode** [comment]
No this don't work and there is a lot of enhancement on the main branch regarding MCP23S08. I assume this will be better by every change. I just updated to 6.2.1.4 and there a again a lot of changes here
