### ISSUE TITLE
MCP230XX used the same way as PCF8574

### ISSUE THREAD

**Issue by MadDoct** [stefanbode/Sonoff-Tasmota#56]
Could you add support for mcp23008 and mcp23017, the same way as PCF8574. I mean allowing them to be set as relays and not as sensors as in the current implementation...

**Comment by stefanbode** [comment]
I just received some modules to test. Also have to see what’s already in the master branch. Anyhow quite busy these days. Time is gold .

**Comment by welbo97** [comment]
Master added support and driver for mcp230xx series and implemented a sensor29 command to control it. I suggest you close this issue.

**Comment by stefanbode** [comment]
Thanx!

**Comment by MadDoct** [comment]
This shouldn't be closed! It wasn't about implementing support for mcp23017. That has been done for a long time and I even helped implementing it... It was about implementing it seamlessly like with pcf8574, being able to configure it as relay or switch from tasmota...
