### ISSUE TITLE
pulsetimers 

### ISSUE THREAD

**Issue by mrmin24** [stefanbode/Sonoff-Tasmota#6]
When switching pulsetimer1 and 5 to 10 sec. If relay 1 is switched on its own it works. If switch 5 is triggered after switch1 while timer still running, switch1 timer is cancelled and switch5 works.

**Comment by stefanbode** [comment]
@mrmin24 : Trying now to get away from all the nasty hardcoded stuff. The issue with the pulsetimer is also now fixed. I assume, if you need more than 8 pulsetimers it is enough just to change the MAX_PULSETIMER constant and compile again.

**Comment by mrmin24** [comment]
@stefanbode Hi, nice work thanks. I am busy testing. So var so good. I have 9 relays including the on-board relay on the SV.
