### ISSUE TITLE
Can someone create (compile) *.bin file??

### ISSUE THREAD

**Issue by abaszczok** [stefanbode/Sonoff-Tasmota#62]
Hi...

I got general issues with Arduino IDE - I can't compile any project..Got several issues with this software, libraaries versions... thx in adv.. I just need software to control roler shutters with position...

**Comment by stefanbode** [comment]
you should use Platform IO IDE, much easier to use. Anyhow I uploaded a sonoff and a wemos version. Please see the bin folder.

**Comment by abaszczok** [comment]
Stefan.. Thank you very much... Now I will spend this night testing your version.. thx
