### ISSUE TITLE
Introduce new interlock mode for testing

### ISSUE THREAD

**Issue by stefanbode** [stefanbode/Sonoff-Tasmota#64]
I made the interlock more flexible. In the past it was interlock with all (setoption 14) or paired with the interlockmask to exclude relays. After some brain fuck of binary operation I introduced a new variable called BUCKETSIZE. This defines the amount of relays belong to the interlock. Default is 2.

**Comment by B1G1** [comment]
Hi stefan,
this new interlock mode affects in some way the shutter mode?

**Comment by stefanbode** [comment]
Hi Bigi, hopefully not. The shutter should use the BUCKTESIZE=2 and should behave as before. I tested quite a lot with the change. Please let me know, if you find a bug.

**Comment by stefanbode** [comment]
I fixed a bug that uses the TASMOTO full interlock if switching OFF a relay that was already OFF
