### ISSUE TITLE
big problem with sonoff 4ch pro

### ISSUE THREAD

**Issue by madmicio** [stefanbode/Sonoff-Tasmota#65]
Hi!
I found a new bug in sonoff 4ch pro mode. use in shutter mode
you are active the relay 1 and before turning it off active the 3 or the 4 by slider. the two relays remain permanently on

same problem with web interface button and physical buttons

if you the two shutter to 
together, the relays remain permanently on or off

more simply if you activate the two shutters at the same time, the relays will remain permanently on

**Comment by stefanbode** [comment]
Yes already found this one too this afternoon after crashing my shutter a bit. The recognition through Alexa was not correct. But it should work without the Hue emulation. Anyhow maybe the same error somewhere else. R1 and r2 are normal and r3-r5 belong to the shutter?

**Comment by madmicio** [comment]
sorry, I think I did not understand the question.
however, relay1 shutteropen1, relay2 shutterclose1, relay3 shutteropen2, relay4 shutterclose2

**Comment by stefanbode** [comment]
Ok now I got it and this is quite serious. I will check this today and get it fixed soon. I thought all variables for the schütter are already separated, but I have an idea which one is missing. The real-time clock. Could get complicated.
