### ISSUE TITLE
shutter sopprt

### ISSUE THREAD

**Issue by mike2nl** [stefanbode/Sonoff-Tasmota#73]
@stefanbode 
Question:
- I ask about the shutter support what is the meaning.

- I ask because i had a shutter idea myself to, but it was meaned for the 
veml6070 and veml6075 to close the sensor against the burning sunlight 
so that the sensor can have a longer lifetime.

Thanks in any case.

**Comment by stefanbode** [comment]
Please take a look at the wiki here to get more information about how the shutter operates and which features it support. Additional question I will answer ASAP.
