### ISSUE TITLE
PW in user_config_override.h?

### ISSUE THREAD

**Issue by vrjpellenz** [stefanbode/Sonoff-Tasmota#8]
Hallo Stefan,

evtl. stehen echte SSID/PW in der Datei user_config_override.h - zumindest sehen die nicht nach Dummy aus ("BodeNet_Keller" etc.)

Grüße
  Johannes

PS: Gibt es einen Trick, den jetzt oft tiefschlafenden ESP wieder länger wach zu halten, um z.B. neue Werte für TelePeriod oder Deepsleep zu setzen (oder das normale Webinterface zu nutzen)? z.B. 
http://192.168.178.56/cm?cmnd=TelePeriod 120

**Comment by stefanbode** [comment]
Ja, deepsleep per mqtt auf 0 setzen und die Message retainen, so dass beim aufwachen diese verarbeitet werden kann. Dann werde ich mal die Passwörter ändern müssen.
