### ISSUE TITLE
Shutters close after reconnect to MQTT Broker

### ISSUE THREAD

**Issue by electrontube** [stefanbode/Sonoff-Tasmota#82]
With MQTT being configured there is an issue with „Shutter Mode“:
If connection to the MQTT Broker is lost and re-established, all Stutter Modules are triggered and Shutters fully close (regardless of the previous position of the shutter).

This is really critical, imagine you are in your Garden... 
a glitch in your WiFi could lock you out of your house.

**Comment by B1G1** [comment]
You have to set retain false on the mqtt side to prevent this kind of issue

**Comment by electrontube** [comment]
Thanks for the hint, but retain is already set to false, that doesn't solve the problem.

**Comment by B1G1** [comment]
May be there is already a retained message. In my case i had to reset the mqtt broker

**Comment by electrontube** [comment]
There shouldn't be any retained messages, as everything was working fine before and there were no outstanding tasks at the point in time the Connection to the broker was reestablished.

**Comment by electrontube** [comment]
Thanks @B1G1 , purging the persistence database helped for the moment, but I still feel there is more to be investigated.

**Comment by stefanbode** [comment]
Please can you set loglevel 5 and send the log after restart. We should easily find out where a command comes from and what happen in detail. The log is your friend

**Comment by electrontube** [comment]
@stefanbode 
The problem appears to be gone after purging the persistence database on the broker.
I will keep an eye on it and report if it occurs again.

**Comment by stefanbode** [comment]
Yes, that sounds reasonable. We do not have this problem elsewhere and the MQTT retain stuff also creates some confusion in the Forum of the TASMOTA main forum. There you will find in the MQTT session also some commands how to delete values. I'm using MQTT-SPY for browsing my values and this works great. But there are also other tools available.
