### ISSUE TITLE
DeepSleep | increase awake time

### ISSUE THREAD

**Issue by AnhDuc85** [stefanbode/Sonoff-Tasmota#85]
Hi,
I'm using the current master branch on wemosD1 with SR04T sensor. I've set DeepSleep via mqtt to 600 and telemetry period to 10.y device wakes up and goes back to DeepSleep without any issues but the time to report the sensor value seems too short. I receive only rssi and vcc values but no value of distance (SR04T). If the device is in normal mode, the distance value is send every 10 seconds.

Any idea how to increase awake time or how to fix this issue?

**Comment by drahdiwaberl** [comment]
sorry for re-opening. but you say teleperiod 15 or 20 should make it more likely to get tele-messages than 10?
in any case i got 3 DS18x20 on a wemos D1 mini and can't seem to get it being awake long enough to tele out - after a manual reboot it takes ~6secs - no matter what period i set :(
