### ISSUE TITLE
after platformio at atom update compilation fails

### ISSUE THREAD

**Issue by roesl** [stefanbode/Sonoff-Tasmota#93]
After updating platformio from atom.io build fails with several errors
With Arduino ide compilation is completed with no errors with same project configuration

**Comment by stefanbode** [comment]
I'm using atom.io and platformio for all of my development and it works fine. Therefore I assume not a general problem. Could you be more specific about the errors? Additionally, platformio takes some time to download all the stuff and dependencies. sometimes it works 10 minutes later.

**Comment by roesl** [comment]
the platformio.ini in the actual zip archive seems not to fit to rest of the Archive - when I use the platformio.ini from  arendst it works.

**Comment by knowsnotmuch** [comment]
An absolute noob here - but I had to rename my_user_config.h to user_config_override.h for it to compile
